# Sensitive environment properties to be hosted by Spring Cloud Config Server can be placed here
# Note, these should be encrypted with the appropriate prefix syntax. This file is usually populated
# during execution of the `flex:generate` maven goal at the time of project construction when the
# config server supporting component is enabled in the manifest. This file is generally placed into a
# git repository which is referenced by Spring Cloud Config Server setup. See `config/README.adoc` for
# more details.

server:
  ssl:
    key-store-password: '{cipher}{key:version_1}AYBPlUABgBMsiA5FxfLyn2qwXB/PmRu9gYFm++LHOl5uxUgfLJ7dfe7ounBFJgSmhiGNbWzRkPRHzHTHGlmP1Xl1tq8e0hnZnk/yzvZouZ+F0AR4zEWglAdLcjWyumvY7Obpz9ddFen8BhEFHNmsCDH/DrIxy6JzxaUrudmDk1w9rftZlKtVpCloNsly/lIC/V/4WrfWHNdQw14v6ioFZVcgmM6Bp0VK2qzfveMsZ4CGYK2Nw5lltwcUDh7qBeRxBsXzfymhkj1Byk0UcUCcWLy9g9gSCv6/nTO4ToaCrv3vea+PQNIrpVunEUAAXKKmKZJeFY/YhMWWaOXcR8uxPb5LlnZ3sStNWstLrI1/PaKp1ytOBMK4/oHIP23xmOSR28tj2SVOOOa8CAl9sQxDd5WBXxbE+paJWpjLeWIS7r8o1Og1bcf8u9AMSaHYS8aByORz9AnzAAYslrzE1yrVXrNHuEW+dFY7gs3zzFag9cG3GPy0bkhEQ8QZ4mVvHS4DpARqSyA3W/QyMXq+AyKTLdlnS+B13hVInCUYbW1KbAMUJofQxZCJnp5aXzoPNyP5m2M='
broadleaf:
  default:
    server:
      ssl:
        key-store: file:/var/keys/https-keystore.jks
    spring:
      cloud:
        stream:
          kafka:
            binder:
              configuration:
                ssl:
                  truststore:
                    location: /var/keys/kafka-truststore.jks
    java:
      security:
        auth:
          login:
            config: /var/keys/zk-kafka-client-jaas.conf
spring:
  cloud:
    stream:
      kafka:
        binder:
          configuration:
            ssl:
              truststore:
                password: '{cipher}{key:version_1}AYAYSGX/8OXpq0oRgzzb3JE2vZDmzinXRzPjarHxduXuS2ueObfNYFaAq0Vxpx2NBlsEwOsXZCiWM7QJVl4DMdHM+Mdi9JeAE+10nkkxAvpv1q91dvqZfYrs8bFCWZRQminhKnKbq6DLJT88c2keN7fh+QPJoAwDsQDthK1o3IjxBWrmegswPumu49qdfHW5XsiV3J//r0Jx9sZX4ibfbzLUCTiS8/+o9TFYp8r48sLAQRTyOOacnYhaHW+CyDC2MinAZOAe+37E1RvArWAG5S3tJ6CMW4GZyKzzFyjclRroNUKccNh1ZWRf+vZzzLN9pnAxgzi/4B3iDhuw51gE1e56Tx3HavEBd41ZKe6GQgSxrYvgmT3HzKfabMIrwKiDqbYqzmTl8NKmtb53xmysdYrxFMQ3AGH/I4oGIK5Jnbl18WFmP+9a6nq2TurstFTa8qZUOuS0xgB+88PPotDgZ/KKlJcgjfw/8kTvM1av4P8hDdGsPJDsJaeACI47vFDfQXY1xqNA8tIhErOlpK2Cp11L87Sfl7z60uRKiX5SH7R2rBrvLNC2fiy4LVQslPvbgN8='
            security:
              protocol: SASL_SSL
            sasl:
              mechanism: PLAIN
  security:
    oauth2:
      client:
        registration:
          anonymous:
            client-secret: '{cipher}{key:version_1}AYA5GBgNmYcPiuUbw0Z3++7UyInocm2pNmZH3y/2tATwbXm2ngR96qvsKAKSM7g/DXDUqmPMhvHU2mWLu4nkRjRCCZV7uVhThs1u68Q97rNSSCJk7MKiUE0RjLAD5oieIsN/ckwUOnCs79vajWu5nNGw4ex5/kQf8ovU2Wdou3Z3NBuVdIodqWlMWggJaGn8peNfsloyUhG0F9eFANL4fOjJ1PfzmvgAOlc8slxyq2+RA9jUm5NX1j+g9FOdnLsYOccaFGpAYiHLueRxUA9A7QnptgEn6m64cL3VdlLZgtTNBdZZY4R0+rOWCG4CvbijXE5iIBpiQOBZQmuKYa8TrgZ6U5pdT4fjaT1OxFo73Xj6OKBeLQTuoMMHkYVCfP4bWGsfwAC6dgqR5YE0FNenFlg36mrmuv4VOvBMMvkACpHV9nl4XwT0z+LjD/O3b8+Ik2BdD2SOQ5ZHZ2vP6fxcRynQlkelWIQiXSwSYQ7sEHb0XlaCDVQt7HgBuga2R6WJ7u/cu8AbVt2hmyK2WgwvmNgFWoJjj5TB6dJVj2gS21O8N1uit2kCJpugq7wYhgxlK5o='
