Server {
       org.apache.zookeeper.server.auth.DigestLoginModule required
       user_super="a1BL3ub68YHVdV84EH6eihBy"
       user_kafka="FirLokP7hS96K0ysc3KT5HQc"
       user_readonly-user="MWkD7SlRr1eyhle3df8lmVSh";
};